name: End2End tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash

env:
  KIND_VERSION: v0.19.0
  OPERATOR_IMAGE_PATH: /tmp/temporal-operator.tar
  WORKER_PROCESS_IMAGE_PATH: /tmp/example-worker-process.tar

jobs:
  run-e2e:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
       kube-version:
       - v1.25.16
       - v1.26.14
       - v1.27.11
       - v1.28.7
       - v1.29.2
    name: Run generate E2E tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: temporal-operator:latest
          cache-from: type=gha
          cache-to: type=gha
          outputs: type=docker,dest=${{ env.OPERATOR_IMAGE_PATH }}
      - name: Build worker-process
        uses: docker/build-push-action@v5
        with:
          context: ./examples/worker-process/helloworld
          push: false
          tags: example-worker-process:latest
          cache-from: type=gha
          cache-to: type=gha
          outputs: type=docker,dest=${{ env.WORKER_PROCESS_IMAGE_PATH }}

      - name: Free some disk space
        run: sudo rm -rf /usr/share/dotnet && sudo rm -rf /opt/ghc && sudo rm -rf "/usr/local/share/boost"
      - name: Run e2e test suite
        run: make test-e2e
        env:
          OPERATOR_IMAGE_PATH: ${{ env.OPERATOR_IMAGE_PATH }}
          WORKER_PROCESS_IMAGE_PATH: ${{ env.WORKER_PROCESS_IMAGE_PATH }}
          KUBERNETES_VERSION: ${{ matrix.kube-version }}
      - name: Archive e2e logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: e2e-artifacts
          path: out/tests/e2e/
